# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 56c8a7e1c2460e42c3a08cc868fdf3d848ccf0294b967d3137907f51066486956cb7a9c9aead9ac0d7decd53de51a93a8aec018233857cba6615e8b7872a4c50

test:
  secret_key_base: 0307afe3193eb5f68b37f9968c6e0f80722906e697812b340916129045f28e291f716b6d5229a6962b6aac07c8d32f653bae9dd8a0e24278941ad467e5376eba

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
